# Sakuli example docker-compose.yml file with different container running the same tests in parrallel

sakuli-cm_assign_ticket:
  build: test_client
  volumes:
  - ./consol_cm_test_suites:/root/my_test_suites
  environment:
  # set correct timezone
  - TZ=Europe/Berlin
  # set Sakuli test suite
  - SAKULI_TEST_SUITE=/root/my_test_suites/test_assign_ticket
  ports:
  #vnc
  - 5911:5901
  #noVNC HTML client
  - 6911:6901

sakuli-cm_attach_pdf:
  build: test_client
  volumes:
  - ./consol_cm_test_suites:/root/my_test_suites
  environment:
  # set correct timezone
  - TZ=Europe/Berlin
  # set Sakuli test suite
  - SAKULI_TEST_SUITE=/root/my_test_suites/test_attach_pdf
  ports:
  #vnc
  - 5912:5901
  #noVNC HTML client
  - 6912:6901

sakuli-cm_comment_ticket:
  build: test_client
  volumes:
  - ./consol_cm_test_suites:/root/my_test_suites
  environment:
  # set correct timezone
  - TZ=Europe/Berlin
  # set Sakuli test suite
  - SAKULI_TEST_SUITE=/root/my_test_suites/test_comment_ticket
  ports:
  #vnc
  - 5913:5901
  #noVNC HTML client
  - 6913:6901

sakuli-cm_check_links:
  build: test_client
  volumes:
  - ./consol_cm_test_suites:/root/my_test_suites
  environment:
  # set correct timezone
  - TZ=Europe/Berlin
  # set Sakuli test suite
  - SAKULI_TEST_SUITE=/root/my_test_suites/test_check_links
  ports:
  #vnc
  - 5914:5901
  #noVNC HTML client
  - 6914:6901